### ISSUE TITLE
[MINOR] 'Continue' button does not function properly when uploading bills

### ISSUE THREAD

**Issue by ndemmel** [info442-sp21/g-team#72]
Severity: I'm unsure if this is a major or minor bug because it is unclear what pressing the 'continue' button does. 

Description: When filling in the bill fields with valid input, pressing the 'continue' button leads back to the bill page where you select a bill you want to learn more about. 

Environment: Windows 10 Firefox 88.0.1 (64-bit)

Steps to reproduce: 
1. Sign in to the application
2. Click "upload your bills" in the bottom right corner
3. Choose any of the 3 bill types
4. Give any valid input for the bill fields
5. Press 'continue'

Actual result: Pressing 'continue' loops the user back to the bill selection page (step 3).

Expected result: Pressing 'continue' takes the user to a page that explains why they paid X dollars for Y amount of water, gas, or electricity.

**Comment by embascom** [comment]
- Rephrase "Which bills do you want to learn about?"
- Have the "Continue" button redirect to the Dashboard -- Rename it to "Submit"
- Reroute and have the dashboard updates

**Comment by embascom** [comment]
Duplicates: https://github.com/info442-sp21/g-team/issues/79

**Comment by haileymeister** [comment]
https://github.com/info442-sp21/g-team/commit/ae57a43a23706833a8c9002dc631eecc123fbc16
