### ISSUE TITLE
Welcome title on the left side of homepage

### ISSUE THREAD

**Issue by atnguyenduy** [info442-sp21/g-team#73]
**Describe bug**
Welcome title should be on the left side of the homepage

**To Reproduce**
1. Go to https://good-team-442.web.app/
2. Log in 
3. See error 

**Expected behavior**
Expected welcoming title on the left side of homepage

**Screenshot**
![image](https://user-images.githubusercontent.com/41980535/119573614-5e862f00-bd69-11eb-81bf-33258e8cd6e9.png)

**Desktop (please complete the following information):**
Device: Lenovo Thinkpad laptop
Windows 10 Enterprise / Version 20H2 / OS build 19042.804
Browser: Edge
Version 90.0.818.56

**Comment by embascom** [comment]
- No real reasoning submitted for this enhancement, therefore we will be sticking with our original design
