### ISSUE TITLE
Remove "sign out" button from nav bar

### ISSUE THREAD

**Issue by smckissick1** [info442-sp21/g-team#74]
Consider removing "Sign Out" button from navigation bar so that users don't accidentally push it when wanting to look around the site (maybe make it its own box instead)

**Comment by embascom** [comment]
- Potentially have nav bar float right and put sign out in a button that's a different color so users don't get confused

**Comment by abq14** [comment]
[Put sign-out on it's own box (resolved original enhancement suggestion). ](b3b1a6c5d2d00f7fed6dc7b87e27ad3c640dc8fd)

Still working on floating some of the navbar elements.

**Comment by haileymeister** [comment]
https://github.com/info442-sp21/g-team/commit/d2736f535092f54b3867f537dd8b7d002f2f16f1 floated sign out right on Navbar
