### ISSUE TITLE
[Major] Bills Dashboard Feature

### ISSUE THREAD

**Issue by jordanjones243** [info442-sp21/g-team#75]
**Problem**
Once a bill is submitted, it looks like on the dashboard your monthly usage is supposed to appear. When I submitted two bills for water and electricity, nothing shows up on the usage dashboard.

**Steps to Reproduce**
1. Go to https://good-team-442.web.app/home
2. Sign in
3. Go to Dashboard
4. Click on Upload your bills
5. Click on the type of bill and enter in bill information
6. Go back to dashboard
7. Look at the bottom to see monthly usage feature

**Environment**
Google Chrome Version 89.0.4389.128 (Official Build) (x86_64)

**Screenshot**
<img width="544" alt="Screen Shot 2021-05-25 at 2 56 42 PM" src="https://user-images.githubusercontent.com/55807669/119573714-82497500-bd69-11eb-8501-62b78a9ebbbd.png">

**Expected Result**
My monthly usage should appear on the dashboard when I have submitted a bill.

**Comment by embascom** [comment]
- Make functionality work.... 
- Have the dashboard update after inputting data
