### ISSUE TITLE
[MINOR] No Validation For Entering A Utility Bill

### ISSUE THREAD

**Issue by kmarshall98** [info442-sp21/g-team#76]
**Description** When entering a utility bill, the user is prompted to enter the month the bill is for, the usage in CCF's, and the US dollars spent.

**Severity** Minor

**Environment** Safari on MacOS BigSur 11.2.3

**Steps**
1) After logging in or signing in, navigate to the dashboard if you are not already there.
2) Press "Upload Your Bills" 
3) Select either water, electricity, or gas
4) Enter in the data (month, usage, and US dollars spent).
Expected Outcome: The user should receive some sort of error when entering information that shouldn't be possible.
Actual Outcome: User is able to enter in a negative number for the usage and a date of bill that is far in the future when they should be able to enter in a bill later. 
<img width="379" alt="Screen Shot 2021-05-25 at 3 07 33 PM" src="https://user-images.githubusercontent.com/46639384/119574846-f1739900-bd6a-11eb-8fc1-585b34a940b5.png">

**Comment by embascom** [comment]
- When trying to enter data, make sure every field of input form is validated

**Comment by embascom** [comment]
Duplicates: https://github.com/info442-sp21/g-team/issues/83

**Comment by haileymeister** [comment]
a23bfafe61db3a5b3f2bd4ad5d124b5ff571475f this commit fixes no negative numbers I have decided that the user should be able to enter in a year in the future because sometimes bills come dated in the future.
