### ISSUE TITLE
[Minor] The 'no data' text still shows if you data in the Past Bills page

### ISSUE THREAD

**Issue by dorilusions** [info442-sp21/g-team#77]
The "You have no _ data" in the "View Past Bills" page shows if you have data in one category (e.g. electricity) and none in others.

To reproduce:
1. Click on 'Upload your bills" and enter a couple bills in one category.
2. Go back to the home page and click on 'View Past Bills'.
3. Click on the category with data.

Screenshot:
![image](https://user-images.githubusercontent.com/43550545/119573940-cfc5e200-bd69-11eb-821f-fc665584ea0a.png)

This was found on Google Chrome ver. 90.0.4430.212 for browser.

**Comment by embascom** [comment]
- Look into Past Bills code and see why it displays "You have no Electric data" shows up all the time

**Comment by haileymeister** [comment]
https://github.com/info442-sp21/g-team/commit/f8e319fe92dc084102ee2e418f349b9efdf49377#diff-a6b4ac3b48f81b828e48e58ff29a04990557f9bc753301a82052fca349328623 This commit fixed this problem.
