### ISSUE TITLE
Sustainability guide resource links only on images [minor]

### ISSUE THREAD

**Issue by mariamatlick** [info442-sp21/g-team#78]
description (general summary of the problem):
When reading the resources column under the sustainability guide, the links for the different resources are unclear. The link is only on the images which wasn't quite clear and at first I thought there were no links at all!

environment:
Chrome Version: Version 90.0.4430.212 (Official Build) (64-bit)
Windows Version: 10.0.19041 Build 19041

steps to reproduce:
1. Log in to website
2. Navigate to Sustainability Guide
3. See error: no visible link for each resource, only indication is the change of cursor over the image (which is confusing because some browser extensions do this automatically for all images, so wasn't sure if it was your site or not!)

actual result:
Link only on image

expected result:
Maybe a "Click here", or have the entire box be a hyperlink, essentially more than just the image have the link to the resource

**Comment by embascom** [comment]
- We think that this is an Enhancement as it is a design issue rather than a functionality issue

**Comment by embascom** [comment]
- make whole box clickable

**Comment by abq14** [comment]
Change completed! https://github.com/info442-sp21/g-team/commit/eb0ccb642c51d2c62f303d1a608606cbb36ed072
