### ISSUE TITLE
Upload Bills Process Flow Endless Loops / No Confirmation Message

### ISSUE THREAD

**Issue by popi1141** [info442-sp21/g-team#79]
1. Go to https://good-team-442.web.app/home
2. Click 'Upload Your Bills'
3. Finish the Flow By Inputting Details About Any Bill 
4. You Get Sent Back to the Start of the Bill Upload Process

May not exactly be a bug, but there's no indication that the user's bill has successfully been submitted -- especially since it sends you back to the beginning of the process. 

I'm on Windows 10 Desktop.

**Comment by embascom** [comment]
- We did not meet our requirements for the continue button rerouting to Dashboard so we will fix this
