### ISSUE TITLE
[MAJOR] Monthly usage is not being updated

### ISSUE THREAD

**Issue by SandyHsiao** [info442-sp21/g-team#80]
Severity: major
Description: After entering the second bill of this month, the information under 'This month you used' section isn't being updated, it only displays the first bill user entered.
Reproduce: Enter the website, upload your bills, select 'water', enter the data (for this month), the data is being updated to the 'This month you used' section, go to upload your bills again, select 'electricity' this time, enter the data (for this month), the data is not being uploaded to the 'This month you used' section.
Environment: Mac OS Catalina, Chrome browser

**Comment by embascom** [comment]
- Again, refine the code for the dashboard so it upload properly

**Comment by brendantran** [comment]
Fixed electricity, water, and gas pictograph.
