### ISSUE TITLE
Better Feedback Messaging for Bill Categories with No Inputs

### ISSUE THREAD

**Issue by popi1141** [info442-sp21/g-team#81]
Right now, only a small pop up text bar shows up when you try to generate the graph for a bill type that you don't have any inputs for. For usability purposes, it might be nice to have either an alert or a bigger text bar.

![image](https://user-images.githubusercontent.com/45519338/119576382-38a16e80-bdeb-11eb-99af-2b892cbb064b.png)

**Comment by embascom** [comment]
- This will be fixed when Brendan finishes the Dashboard

**Comment by haileymeister** [comment]
7909074708e83c944591b5609a832a0da02c9979 should have been fixed in this commit
