### ISSUE TITLE
[Minor] When in mobile/smaller screen view, after you click on the hamburger menu ~5+ times, it stops working

### ISSUE THREAD

**Issue by yiuchungcheung** [info442-sp21/g-team#82]
Describe the bug
On smaller screens such as mobile view, when you keep clicking on the hamburger menu for the dropdown more than about 5 times, the dropdown stays open and stops working.

severity Minor

To Reproduce

Shrink screen size or just go to website on mobile phone
Click on hamburger menu for about 5 times
See error

Expected behavior
The hamburger menu should always be working rather than just work the first couple of times of usage.

Desktop (please complete the following information):

OS: Windows 10 Home
Browser Chrome (smaller screen size)
Version 90.0.4430.212

**Comment by embascom** [comment]
- Make hamburger menu go away on mobile version -- active/inactive state

**Comment by haileymeister** [comment]
https://github.com/info442-sp21/g-team/pull/90/commits/30645f420590882472a7fb691e7df706ad499faa This commit fixes the issue of the nabber not closing.

**Comment by cherimarie** [comment]
What an interesting bug! Good catch, Jacky.
