### ISSUE TITLE
Negative KWHs

### ISSUE THREAD

**Issue by gidchia** [info442-sp21/g-team#83]
The page allows me to enter negative KWHs. This might be an issue for error handling.

**Describe:**
When inputting KWHs under electricity, the user has the option of inputting negative values.

**To Reproduce:**
1. Click on "Upload your Bills"
2. Click on "Electricity"
3. Click on the "Down" button under "Usage in KWHs"

**Expected Behavior:**
Only positive KWH values can be inputted

**Desktop (please complete the following information):**
OS: iOS
Browser - Chrome
Version - Version 90.0.4430.85

**Comment by embascom** [comment]
- Validate input forms
