### ISSUE TITLE
[Minor]Default to Log In

### ISSUE THREAD

**Issue by sonalichan** [info442-sp21/g-team#84]
Default to the Log In tab on the sign up page. Might be confusing for people who don't really pay attention while inputting their information.

To Reproduce:

Open the website or click on the sign out tab if already signed in
Click on the Log In tab instead of the sign up tab

Desktop (please complete the following information):
OS: Windows 10
Browser - Chrome
Version - Version 90.0.4430.212

**Comment by embascom** [comment]
- Switch Sign Up and Sign In on the landing page -- if they log out it should reroute to Sign In

**Comment by haileymeister** [comment]
https://github.com/info442-sp21/g-team/pull/89/commits/036bad6ad940cb08b6e83b2cb0cbf4c726ea090a This commit fixes the sign out routing.
