### ISSUE TITLE
Add Units to Past Bills

### ISSUE THREAD

**Issue by brendantran** [info442-sp21/g-team#93]
The current past bills only display the number the user uploaded with no units. This may be confusing for the user if they don't know what units correspond to each utility.

1. Go to Past Bills
2. Go to a tab that has a bill uploaded.
3. See that there are no units after the number.

**Comment by haileymeister** [comment]
https://github.com/info442-sp21/g-team/commit/625ea031bb3f60f4f93a438c92719394fbe947a9 this commit fixes this
