### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by waheedahakim** [info442-sp21/g-team#95]
over all a very good idea. I tried to enter the month in the format asked but it wont let me type 05/2021 instead it picks the month in words if i type 05/2021 it converts it to May, 2021. the calendar is convenient but it doesn't align with the required format as the error is shown in the screen shot so it would be nice to be flexible on that restriction based on the format of the provided calendar. if users cant use it then i wonder what was the initial point of it to be there.

![image](https://user-images.githubusercontent.com/43686537/120703991-ddb2eb80-c46a-11eb-8fc0-3afc3a1b1da5.png)

**Comment by changz23-1836696** [comment]
I am able to type in month with the proper format by deleting the "type" property of the input form in the inspector, so this could be a simple fix.
<img width="752" alt="Screen Shot 2021-06-03 at 3 46 22 PM" src="https://user-images.githubusercontent.com/43832007/120721598-0515b280-c483-11eb-96ee-0a1ea754b791.png">

**Comment by haileymeister** [comment]
https://github.com/info442-sp21/g-team/commit/d2736f535092f54b3867f537dd8b7d002f2f16f1 fixed in this commit
